// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxvjlmpcmmaldujgblrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4dmpsbXBjbW1hbGR1amdibHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDE4MzcsImV4cCI6MjA2NTExNzgzN30.ng_QCibQqss88nZKd_r70papf1hAW8iqNzDXzjg39zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});